### ISSUE TITLE
Is 'Of' a wanted semantic role?

### ISSUE THREAD

**Issue by TaniaBladier** [texttheater/pmb2tsv#14]
Like in "South of Russia", gold data, file p43/d3000, English. 

'South' is marked as the predicate, and 'of Russia' is the corresponding semantic role with the label 'Of'. I am not sure about this, maybe this semantic role is fine.

**Comment by texttheater** [comment]
Yes, from the perspective of the PMB, `Of` is a wanted semantic role. I think the PMB uses VerbNet/LIRICS roles for verbal predicates, but another set of roles for nominal predicates. I am not entirely sure what that set is, but `Of` seems to be part of it. So in any case this is not an issue with pmb2tsv. Of course, depending on your use case, you may choose to filter the output to e.g. only keep verbal predicates, only certain roles etc.
