### ISSUE TITLE
'How many people in U.S. do not have health~insurance ?

### ISSUE THREAD

**Issue by TaniaBladier** [texttheater/pmb2tsv#45]
Missing SRL "Location"

[https://pmb.let.rug.nl/explorer/phrase.php?q=health%7Einsurance](https://pmb.let.rug.nl/explorer/phrase.php?q=health%7Einsurance)

1	How	QUE	how	3	(s:wq/(s:dcl\np))/n	fa(s:wq, fa(s:wq/(s:dcl\np), * 	O	Pivot
2	many	QUV	?	3	n/n	ba(n, fa(n, * 	O	Pivot
3	people	CON	person	8	n	* )	person.n.01	Pivot
4	in	REL	in	5	(n\n)/np	fa(n\n, * 	O	Pivot
5	U.S.	GPE	u.s.	3	n	lx(np, n, * ))))	country.n.02	Pivot
6	do	NOW	do	8	(s:dcl\np)/(s:b\np)	fa(s:dcl\np, bxc((s:dcl\np)/(s:b\np), * 	O	O
7	not	NOT	not	8	(s\np)\(s\np)	* )	O	O
8	have	EXS	have	0	(s:b\np)/np	rp(s:b\np, fa(s:b\np, * 	have.v.02	V
9	health~insurance	CON	health~insurance	8	n	lx(np, n, * ))	health_insurance.n.01	Theme
10	?	QUE	?	8	.	* ))))	O	O

**Comment by texttheater** [comment]
Is this not as expected? Because this is a noun role, not a verb role.

**Comment by TaniaBladier** [comment]
Oh yes, you're right! I'll close this issue
