### ISSUE TITLE
'She lost Mary'

### ISSUE THREAD

**Issue by TaniaBladier** [texttheater/pmb2tsv#47]
Missing SRL 'Agent'

[https://pmb.let.rug.nl/explorer/explore.php?part=00&doc_id=1929&type=drs.xml&alignment_language=en](https://pmb.let.rug.nl/explorer/explore.php?part=00&doc_id=1929&type=drs.xml&alignment_language=en
)
1	She	PRO	female	2	np	ba(s:dcl, * 	female.n.02	Theme
2	lost	EPS	lose	0	(s:dcl\np)/np	fa(s:dcl\np, * 	lose.v.06	V
3	Mary	PER	mary	2	n	rp(np, lx(np, n, * )	female.n.02	O
4	.	NIL	.	3	.	* ))))	O	O

**Comment by texttheater** [comment]
It's an annotation error in the PMB (*She* and *Mary* are incorrectly annotated as coreferring). I reported it there.
