### ISSUE TITLE
'What a lot of books!'

### ISSUE THREAD

**Issue by TaniaBladier** [texttheater/pmb2tsv#49]
Should not Co-Theme start at the word "books"?

[https://pmb.let.rug.nl/explorer/explore.php?part=00&doc_id=1824&type=der.xml&alignment_language=](https://pmb.let.rug.nl/explorer/explore.php?part=00&doc_id=1824&type=der.xml&alignment_language=
)
1	What	EMP	what	3	s:dcl/np	fa(s:dcl, * 	O	V
2	a	DIS	a	3	np/n	fa(np, * 	O	Co-Theme
3	lot	QUV	+	0	n/pp	fa(n, * 	O	O
4	of	REL	of	5	pp/np	fa(pp, * 	O	O
5	books	CON	book	3	n	rp(np, lx(np, n, * )	book.n.02	O
6	!	EMP	!	5	.	* ))))))	O	O

**Comment by texttheater** [comment]
I think the whole phrase *a lot of books* is supposed to be the Co-Theme.
